# Change these first
owner: hamannjens # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DBA1
    url: https://dba1.jenshamann.solutions
    maxResponseTime: 3000
    headers:
    - "Authorization: Basic $DBA1_AUTH"
  - name: Glances1
    url: https://glances1.jenshamann.solutions
    maxResponseTime: 3000
    headers:
    - "Authorization: Basic $GLANCES1_AUTH"
  - name: Grafana1
    url: https://grafana1.jenshamann.solutions
    maxResponseTime: 3000
    headers:
    - "Authorization: Basic $GRAFANA1_AUTH"
  - name: Health1
    url: https://health1.jenshamann.solutions
    maxResponseTime: 3000
  - name: CICD
    url: https://cicd.jenshamann.solutions/userContent/readme.txt
    maxResponseTime: 3000
  - name: Prometheus1
    url: https://prometheus1.jenshamann.solutions
    maxResponseTime: 3000
    headers:
    - "Authorization: Basic $PROMETHEUS1_AUTH"
  - name: WeatherV1
    url: https://wetter.jenshamann.solutions
    maxResponseTime: 3000
    headers:
    - "Authorization: Basic $WEATHER_V1_AUTH"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.jenshamann.solutions
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Jens Hamann Solutions"
  introMessage: This is my status page for all my servers and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
