# Change these first
owner: hamannjens # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Host1
    type: "globalping"
    location: $GLOBALPING_REGION_B
    check: "tcp-ping"
    url: $HOST1_IPV4
    #port: $HOST1_TCP_PING_PORT
    maxResponseTime: 150
  - name: Host3
    type: "globalping"
    location: $GLOBALPING_REGION_N
    check: "tcp-ping"
    url: $HOST3_IPV4
    #port: $HOST3_TCP_PING_PORT
    maxResponseTime: 150
  - name: Host4
    type: "globalping"
    location: $GLOBALPING_REGION_N
    check: "tcp-ping"
    url: $HOST4_IPV4
    #port: $HOST4_TCP_PING_PORT
    maxResponseTime: 150
  - name: Host5
    type: "globalping"
    location: $GLOBALPING_REGION_F
    check: "tcp-ping"
    url: $HOST5_IPV4
    #port: $HOST5_TCP_PING_PORT
    maxResponseTime: 150
  #- name: CICD
  #  #url: $CICD1_URL
  #  url: https://cicd.jenshamann.solutions/userContent/readme.txt
  #  maxResponseTime: 1500
  #- name: DBA1
  #  url: $DBA1_URL
  #  maxResponseTime: 1500
  #  headers:
  #  - "Authorization: Basic $DBA1_AUTH"
  #- name: Glances1
  #  url: $GLANCES1_URL
  #  maxResponseTime: 1500
  #  headers:
  #  - "Authorization: Basic $GLANCES1_AUTH"
  #- name: Grafana1
  #  url: $GRAFANA1_URL
  #  maxResponseTime: 1500
  #  headers:
  #  - "Authorization: Basic $GRAFANA1_AUTH"
  - name: Health1
    url: $HEALTH1_URL
    type: "globalping"
    location: $GLOBALPING_REGION_B
    maxResponseTime: 150
  #- name: Prometheus1
  #  url: $PROMETHEUS1_URL
  #  maxResponseTime: 1500
  #  headers:
  #  - "Authorization: Basic $PROMETHEUS1_AUTH"
  #- name: WeatherV1
  #  url: $HEALTH1_URL
  #  maxResponseTime: 1500
  #  headers:
  #  - "Authorization: Basic $WEATHER_V1_AUTH"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jenshamann.solutions
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Jens Hamann Solutions"
  introMessage: This is my status page for all my servers and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
